name: Update Cyber Policy Feeds

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours UTC
  workflow_dispatch:          # allows manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run feed fetcher
        run: python fetch_feeds.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/articles.json
          git commit -m "Automated feed update" || echo "No changes"
          git push
